<?php

if ( ! function_exists( 'app_name' ) ) {
	/**
	 * Helper to grab the application name.
	 *
	 * @return mixed
	 */
	function app_name() {
		return config( 'app.name' );
	}
}

if ( ! function_exists( 'gravatar' ) ) {
	/**
	 * Access the gravatar helper.
	 */
	function gravatar() {
		return app( 'gravatar' );
	}
}

if ( ! function_exists( 'home_route' ) ) {
	/**
	 * Return the route to the "home" page depending on authentication/authorization status.
	 *
	 * @return string
	 */
	function home_route() {
		if ( auth()->check() ) {
			if ( auth()->user()->can( 'view backend' ) ) {
				return 'admin.dashboard';
			}

			return 'frontend.user.dashboard';
		}

		return 'frontend.index';
	}
}

if ( ! function_exists( 'headlines' ) ) {
	/**
	 * Fetch Headlines.
	 */
	function headlines( $limiter = 15 ) {
		$object = new \DB();
		$object = DB::table( 'articles' )->select( 'title', 'slug', 'urlToImage' )->inRandomOrder()->limit( $limiter )->get()->toArray();
		return collect( $object );
	}
}

if ( ! function_exists( 'format_news_content' ) ) {
	/**
	 * Formats content for view.
	 *
	 * @return string
	 */
	function format_news_content( $content ) {
		$output = '';

		if ( stripos( '\r\n', $content ) ) {
			$content = explode( '\r\n', $content );

			foreach ( $content as $contentTuple ) {
				$output .= sprintf( '<p class="f1-s-11 cl6 p-b-25">%s</p><br>', $contentTuple );

			}
			return $output;
		} else {
			return sprintf( '<p class="f1-s-11 cl6 p-b-25">%s</p><br>', $content );
		}
	}
}


if ( ! function_exists( 'all_countries' ) ) {
	/**
	 * Return the all countries.
	 *
	 * @return array
	 */
	function all_countries() {
		return array(
			'af' => 'Afghanistan',
			'ax' => 'Åland Islands',
			'al' => 'Albania',
			'dz' => 'Algeria',
			'as' => 'American Samoa',
			'ad' => 'Andorra',
			'ao' => 'Angola',
			'ai' => 'Anguilla',
			'aq' => 'Antarctica',
			'ag' => 'Antigua and Barbuda',
			'ar' => 'Argentina',
			'am' => 'Armenia',
			'aw' => 'Aruba',
			'au' => 'Australia',
			'at' => 'Austria',
			'az' => 'Azerbaijan',
			'bs' => 'Bahamas',
			'bh' => 'Bahrain',
			'bd' => 'Bangladesh',
			'bb' => 'Barbados',
			'by' => 'Belarus',
			'be' => 'Belgium',
			'bz' => 'Belize',
			'bj' => 'Benin',
			'bm' => 'Bermuda',
			'bt' => 'Bhutan',
			'bo' => 'Bolivia',
			'ba' => 'Bosnia and H.',
			'bw' => 'Botswana',
			'bv' => 'Bouvet Island',
			'br' => 'Brazil',
			'io' => 'British (Ocean)',
			'bn' => 'Brunei Darussalam',
			'bg' => 'Bulgaria',
			'bf' => 'Burkina Faso',
			'bi' => 'Burundi',
			'cv' => 'Cabo Verde',
			'kh' => 'Cambodia',
			'cm' => 'Cameroon',
			'ca' => 'Canada',
			'ky' => 'Cayman Islands',
			'cf' => 'Central African Republic',
			'td' => 'Chad',
			'cl' => 'Chile',
			'cn' => 'China',
			'cx' => 'Christmas Island',
			'cc' => 'Cocos Islands',
			'co' => 'Colombia',
			'km' => 'Comoros',
			'cg' => 'Congo',
			'cd' => 'Congo (Republic)',
			'ck' => 'Cook Islands',
			'cr' => 'Costa Rica',
			'ci' => 'Côte d\'Ivoire',
			'hr' => 'Croatia',
			'cu' => 'Cuba',
			'cw' => 'Curaçao',
			'cy' => 'Cyprus',
			'cz' => 'Czech Republic',
			'dk' => 'Denmark',
			'dj' => 'Djibouti',
			'dm' => 'Dominica',
			'do' => 'Dominican Republic',
			'ec' => 'Ecuador',
			'eg' => 'Egypt',
			'sv' => 'El Salvador',
			'gq' => 'Equatorial Guinea',
			'er' => 'Eritrea',
			'ee' => 'Estonia',
			'et' => 'Ethiopia',
			'fk' => 'Falkland Islands (Malvinas)',
			'fo' => 'Faroe Islands',
			'fj' => 'Fiji',
			'fi' => 'Finland',
			'fr' => 'France',
			'gf' => 'French Guiana',
			'pf' => 'French Polynesia',
			'tf' => 'French Southern Territories',
			'ga' => 'Gabon',
			'gm' => 'Gambia',
			'ge' => 'Georgia',
			'de' => 'Germany',
			'gh' => 'Ghana',
			'gi' => 'Gibraltar',
			'gr' => 'Greece',
			'gl' => 'Greenland',
			'gd' => 'Grenada',
			'gp' => 'Guadeloupe',
			'gu' => 'Guam',
			'gt' => 'Guatemala',
			'gg' => 'Guernsey',
			'gn' => 'Guinea',
			'gw' => 'Guinea-Bissau',
			'gy' => 'Guyana',
			'ht' => 'Haiti',
			'hm' => 'Heard Island',
			'hn' => 'Honduras',
			'hk' => 'Hong Kong',
			'hu' => 'Hungary',
			'is' => 'Iceland',
			'in' => 'India',
			'id' => 'Indonesia',
			'ir' => 'Iran',
			'iq' => 'Iraq',
			'ie' => 'Ireland',
			'im' => 'Isle of Man',
			'il' => 'Israel',
			'it' => 'Italy',
			'jm' => 'Jamaica',
			'jp' => 'Japan',
			'je' => 'Jersey',
			'jo' => 'Jordan',
			'kz' => 'Kazakhstan',
			'ke' => 'Kenya',
			'ki' => 'Kiribati',
			'kp' => 'N. Korea',
			'kr' => 'S. Korea',
			'kw' => 'Kuwait',
			'kg' => 'Kyrgyzstan',
			'la' => 'Laos',
			'lv' => 'Latvia',
			'lb' => 'Lebanon',
			'ls' => 'Lesotho',
			'lr' => 'Liberia',
			'ly' => 'Libya',
			'li' => 'Liechtenstein',
			'lt' => 'Lithuania',
			'lu' => 'Luxembourg',
			'mo' => 'Macao',
			'mk' => 'Macedonia',
			'mg' => 'Madagascar',
			'mw' => 'Malawi',
			'my' => 'Malaysia',
			'mv' => 'Maldives',
			'ml' => 'Mali',
			'mt' => 'Malta',
			'mh' => 'Marshall Islands',
			'mq' => 'Martinique',
			'mr' => 'Mauritania',
			'mu' => 'Mauritius',
			'yt' => 'Mayotte',
			'mx' => 'Mexico',
			'fm' => 'Micronesia (Federated States of)',
			'md' => 'Moldova (Republic of)',
			'mc' => 'Monaco',
			'mn' => 'Mongolia',
			'me' => 'Montenegro',
			'ms' => 'Montserrat',
			'ma' => 'Morocco',
			'mz' => 'Mozambique',
			'mm' => 'Myanmar',
			'na' => 'Namibia',
			'nr' => 'Nauru',
			'np' => 'Nepal',
			'nl' => 'Netherlands',
			'nc' => 'New Caledonia',
			'nz' => 'New Zealand',
			'ni' => 'Nicaragua',
			'ne' => 'Niger',
			'ng' => 'Nigeria',
			'nu' => 'Niue',
			'nf' => 'Norfolk Island',
			'mp' => 'Northern Mariana Islands',
			'no' => 'Norway',
			'om' => 'Oman',
			'pk' => 'Pakistan',
			'pw' => 'Palau',
			'ps' => 'Palestine (State of)',
			'pa' => 'Panama',
			'pg' => 'Papua New Guinea',
			'py' => 'Paraguay',
			'pe' => 'Peru',
			'ph' => 'Philippines',
			'pn' => 'Pitcairn',
			'pl' => 'Poland',
			'pt' => 'Portugal',
			'pr' => 'Puerto Rico',
			'qa' => 'Qatar',
			're' => 'Réunion',
			'ro' => 'Romania',
			'ru' => 'Russia',
			'rw' => 'Rwanda',
			'bl' => 'St. Barthélemy',
			'sh' => 'St. Helena',
			'kn' => 'St. Kitts and Nevis',
			'lc' => 'St. Lucia',
			'mf' => 'St. Martin (Fr)',
			'pm' => 'St. Pierre',
			'vc' => 'St. Vincent',
			'ws' => 'Samoa',
			'sm' => 'San Marino',
			'st' => 'Sao Tome',
			'sa' => 'Saudi Arabia',
			'sn' => 'Senegal',
			'rs' => 'Serbia',
			'sc' => 'Seychelles',
			'sl' => 'Sierra Leone',
			'sg' => 'Singapore',
			'sx' => 'Sint Maarten',
			'sk' => 'Slovakia',
			'si' => 'Slovenia',
			'sb' => 'Solomon Islands',
			'so' => 'Somalia',
			'za' => 'South Africa',
			'gs' => 'Georgia Islands',
			'ss' => 'South Sudan',
			'es' => 'Spain',
			'lk' => 'Sri Lanka',
			'sd' => 'Sudan',
			'sr' => 'Suriname',
			'sj' => 'Svalbard',
			'sz' => 'Swaziland',
			'se' => 'Sweden',
			'ch' => 'Switzerland',
			'sy' => 'Syria',
			'tw' => 'Taiwan',
			'tj' => 'Tajikistan',
			'tz' => 'Tanzania',
			'th' => 'Thailand',
			'tl' => 'Timor-Leste',
			'tg' => 'Togo',
			'tk' => 'Tokelau',
			'to' => 'Tonga',
			'tt' => 'Trinidad & To.',
			'tn' => 'Tunisia',
			'tr' => 'Turkey',
			'tm' => 'Turkmenistan',
			'tc' => 'Turks Islands',
			'tv' => 'Tuvalu',
			'ug' => 'Uganda',
			'ua' => 'Ukraine',
			'ae' => 'U.A.E.',
			'gb' => 'United Kingdom',
			'us' => 'U.S.A',
			'um' => 'U.S. Islands',
			'uy' => 'Uruguay',
			'uz' => 'Uzbekistan',
			'vu' => 'Vanuatu',
			'va' => 'Vatican City State',
			've' => 'Venezuela',
			'vn' => 'Viet Nam',
			'vg' => 'Virgin Islands (British)',
			'vi' => 'Virgin Islands (U.S.)',
			'wf' => 'Wallis and Futuna',
			'eh' => 'Western Sahara',
			'ye' => 'Yemen',
			'zh' => 'Zhōngwén',
			'zm' => 'Zambia',
			'zw' => 'Zimbabwe',
		);
	}
}


if ( ! function_exists( 'to_country' ) ) {
	/**
	 * Return the country's name.
	 *
	 * @return array
	 */
	function to_country( $country ) {
		return array(
			'AF' => 'Afghanistan',
			'AX' => 'Åland Islands',
			'AL' => 'Albania',
			'DZ' => 'Algeria',
			'AS' => 'American Samoa',
			'AD' => 'Andorra',
			'AO' => 'Angola',
			'AI' => 'Anguilla',
			'AQ' => 'Antarctica',
			'AG' => 'Antigua and Barbuda',
			'AR' => 'Argentina',
			'AM' => 'Armenia',
			'AW' => 'Aruba',
			'AU' => 'Australia',
			'AT' => 'Austria',
			'AZ' => 'Azerbaijan',
			'BS' => 'Bahamas',
			'BH' => 'Bahrain',
			'BD' => 'Bangladesh',
			'BB' => 'Barbados',
			'BY' => 'Belarus',
			'BE' => 'Belgium',
			'BZ' => 'Belize',
			'BJ' => 'Benin',
			'BM' => 'Bermuda',
			'BT' => 'Bhutan',
			'BO' => 'Bolivia (Plurinational State of)',
			'BA' => 'Bosnia and Herzegovina',
			'BW' => 'Botswana',
			'BV' => 'Bouvet Island',
			'BR' => 'Brazil',
			'IO' => 'British Indian Ocean Territory',
			'BN' => 'Brunei Darussalam',
			'BG' => 'Bulgaria',
			'BF' => 'Burkina Faso',
			'BI' => 'Burundi',
			'CV' => 'Cabo Verde',
			'KH' => 'Cambodia',
			'CM' => 'Cameroon',
			'CA' => 'Canada',
			'KY' => 'Cayman Islands',
			'CF' => 'Central African Republic',
			'TD' => 'Chad',
			'CL' => 'Chile',
			'CN' => 'China',
			'CX' => 'Christmas Island',
			'CC' => 'Cocos (Keeling) Islands',
			'CO' => 'Colombia',
			'KM' => 'Comoros',
			'CG' => 'Congo',
			'CD' => 'Congo (Democratic Republic of the)',
			'CK' => 'Cook Islands',
			'CR' => 'Costa Rica',
			'CI' => 'Côte d\'Ivoire',
			'HR' => 'Croatia',
			'CU' => 'Cuba',
			'CW' => 'Curaçao',
			'CY' => 'Cyprus',
			'CZ' => 'Czech Republic',
			'DK' => 'Denmark',
			'DJ' => 'Djibouti',
			'DM' => 'Dominica',
			'DO' => 'Dominican Republic',
			'EC' => 'Ecuador',
			'EG' => 'Egypt',
			'SV' => 'El Salvador',
			'GQ' => 'Equatorial Guinea',
			'ER' => 'Eritrea',
			'EE' => 'Estonia',
			'ET' => 'Ethiopia',
			'FK' => 'Falkland Islands (Malvinas)',
			'FO' => 'Faroe Islands',
			'FJ' => 'Fiji',
			'FI' => 'Finland',
			'FR' => 'France',
			'GF' => 'French Guiana',
			'PF' => 'French Polynesia',
			'TF' => 'French Southern Territories',
			'GA' => 'Gabon',
			'GM' => 'Gambia',
			'GE' => 'Georgia',
			'DE' => 'Germany',
			'GH' => 'Ghana',
			'GI' => 'Gibraltar',
			'GR' => 'Greece',
			'GL' => 'Greenland',
			'GD' => 'Grenada',
			'GP' => 'Guadeloupe',
			'GU' => 'Guam',
			'GT' => 'Guatemala',
			'GG' => 'Guernsey',
			'GN' => 'Guinea',
			'GW' => 'Guinea-Bissau',
			'GY' => 'Guyana',
			'HT' => 'Haiti',
			'HM' => 'Heard Island and McDonald Islands',
			'HN' => 'Honduras',
			'HK' => 'Hong Kong',
			'HU' => 'Hungary',
			'IS' => 'Iceland',
			'IN' => 'India',
			'ID' => 'Indonesia',
			'IR' => 'Iran (Islamic Republic of)',
			'IQ' => 'Iraq',
			'IE' => 'Ireland (Republic of)',
			'IM' => 'Isle of Man',
			'IL' => 'Israel',
			'IT' => 'Italy',
			'JM' => 'Jamaica',
			'JP' => 'Japan',
			'JE' => 'Jersey',
			'JO' => 'Jordan',
			'KZ' => 'Kazakhstan',
			'KE' => 'Kenya',
			'KI' => 'Kiribati',
			'KP' => 'Korea (Democratic People\'s Republic of)',
			'KR' => 'Korea (Republic of)',
			'KW' => 'Kuwait',
			'KG' => 'Kyrgyzstan',
			'LA' => 'Lao People\'s Democratic Republic',
			'LV' => 'Latvia',
			'LB' => 'Lebanon',
			'LS' => 'Lesotho',
			'LR' => 'Liberia',
			'LY' => 'Libya',
			'LI' => 'Liechtenstein',
			'LT' => 'Lithuania',
			'LU' => 'Luxembourg',
			'MO' => 'Macao',
			'MK' => 'Macedonia (Republic of)',
			'MG' => 'Madagascar',
			'MW' => 'Malawi',
			'MY' => 'Malaysia',
			'MV' => 'Maldives',
			'ML' => 'Mali',
			'MT' => 'Malta',
			'MH' => 'Marshall Islands',
			'MQ' => 'Martinique',
			'MR' => 'Mauritania',
			'MU' => 'Mauritius',
			'YT' => 'Mayotte',
			'MX' => 'Mexico',
			'FM' => 'Micronesia (Federated States of)',
			'MD' => 'Moldova (Republic of)',
			'MC' => 'Monaco',
			'MN' => 'Mongolia',
			'ME' => 'Montenegro',
			'MS' => 'Montserrat',
			'MA' => 'Morocco',
			'MZ' => 'Mozambique',
			'MM' => 'Myanmar',
			'NA' => 'Namibia',
			'NR' => 'Nauru',
			'NP' => 'Nepal',
			'NL' => 'Netherlands',
			'NC' => 'New Caledonia',
			'NZ' => 'New Zealand',
			'NI' => 'Nicaragua',
			'NE' => 'Niger',
			'NG' => 'Nigeria',
			'NU' => 'Niue',
			'NF' => 'Norfolk Island',
			'MP' => 'Northern Mariana Islands',
			'NO' => 'Norway',
			'OM' => 'Oman',
			'PK' => 'Pakistan',
			'PW' => 'Palau',
			'PS' => 'Palestine (State of)',
			'PA' => 'Panama',
			'PG' => 'Papua New Guinea',
			'PY' => 'Paraguay',
			'PE' => 'Peru',
			'PH' => 'Philippines',
			'PN' => 'Pitcairn',
			'PL' => 'Poland',
			'PT' => 'Portugal',
			'PR' => 'Puerto Rico',
			'QA' => 'Qatar',
			'RE' => 'Réunion',
			'RO' => 'Romania',
			'RU' => 'Russian Federation',
			'RW' => 'Rwanda',
			'BL' => 'Saint Barthélemy',
			'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
			'KN' => 'Saint Kitts and Nevis',
			'LC' => 'Saint Lucia',
			'MF' => 'Saint Martin (French part)',
			'PM' => 'Saint Pierre and Miquelon',
			'VC' => 'Saint Vincent and the Grenadines',
			'WS' => 'Samoa',
			'SM' => 'San Marino',
			'ST' => 'Sao Tome and Principe',
			'SA' => 'Saudi Arabia',
			'SN' => 'Senegal',
			'RS' => 'Serbia',
			'SC' => 'Seychelles',
			'SL' => 'Sierra Leone',
			'SG' => 'Singapore',
			'SX' => 'Sint Maarten (Dutch part)',
			'SK' => 'Slovakia',
			'SI' => 'Slovenia',
			'SB' => 'Solomon Islands',
			'SO' => 'Somalia',
			'ZA' => 'South Africa',
			'GS' => 'South Georgia and the South Sandwich Islands',
			'SS' => 'South Sudan',
			'ES' => 'Spain',
			'LK' => 'Sri Lanka',
			'SD' => 'Sudan',
			'SR' => 'Suriname',
			'SJ' => 'Svalbard and Jan Mayen',
			'SZ' => 'Swaziland',
			'SE' => 'Sweden',
			'CH' => 'Switzerland',
			'SY' => 'Syrian Arab Republic',
			'TW' => 'Taiwan, Province of China',
			'TJ' => 'Tajikistan',
			'TZ' => 'Tanzania (United Republic of)',
			'TH' => 'Thailand',
			'TL' => 'Timor-Leste',
			'TG' => 'Togo',
			'TK' => 'Tokelau',
			'TO' => 'Tonga',
			'TT' => 'Trinidad and Tobago',
			'TN' => 'Tunisia',
			'TR' => 'Turkey',
			'TM' => 'Turkmenistan',
			'TC' => 'Turks and Caicos Islands',
			'TV' => 'Tuvalu',
			'UG' => 'Uganda',
			'UA' => 'Ukraine',
			'AE' => 'United Arab Emirates',
			'GB' => 'United Kingdom',
			'US' => 'United States of America',
			'UM' => 'United States Minor Outlying Islands',
			'UY' => 'Uruguay',
			'UZ' => 'Uzbekistan',
			'VU' => 'Vanuatu',
			'VA' => 'Vatican City State',
			'VE' => 'Venezuela (Bolivarian Republic of)',
			'VN' => 'Viet Nam',
			'VG' => 'Virgin Islands (British)',
			'VI' => 'Virgin Islands (U.S.)',
			'WF' => 'Wallis and Futuna',
			'EH' => 'Western Sahara',
			'YE' => 'Yemen',
			'ZH' => 'Zhōngwén',
			'ZM' => 'Zambia',
			'ZW' => 'Zimbabwe',
		)[ strtoupper( $country ) ];
	}
}
